server:
  port: 8095

spring:
  application:
    name: feed-service

  # Include a file with properties
  config:
    import: optional:file:.env[.properties]

  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  data:
    jdbc:
      dialect: postgresql

  # Broker
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}

# For JWT
token:
  signing:
    key: 413F4428472B4B6250655368566D5970337336763979244226452948404D6351